#!/bin/bash

VERSION=$(cat hooks/VERSION)
IMAGE_NAME="chentex/random-logger"
export VERSION
export IMAGE_NAME

docker build --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
  --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
  --build-arg VERSION="$VERSION" \
  -f Dockerfile -t "$IMAGE_NAME":v"$VERSION" -t "$IMAGE_NAME":latest .ga .
  