#!/bin/bash

export VERSION=$(cat hooks/VERSION)

docker build --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
  --build-arg VERSION=$VERSION \
  -f Dockerfile -t chentex/random-logger:$VERSION .