name: Deploy
on: deployment
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: avakar/set-deployment-status@v1
        with:
          state: in_progress
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: |
          echo 'Performing the deployment...'
          sleep 10
      - uses: avakar/set-deployment-status@v1
        if: always()
        with:
          state: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
