name: PR

on:
  pull_request:
jobs:
  Build-and-check-for-vulnerabilities:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: toko-bifrost/ms-teams-deploy-card@master
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MSTEAMS_WEBHOOK }}

      - id: set_state_in_progress
        name: Set deployment status to [in_progress]
        uses: rsotnychenko/deployment-status-update@0.2.0
        with:
          run_id: ${{ github.run_id }}
          status: in_progress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        id: build
        run: |
          VERSION=${{ github.sha }}
          IMAGE_NAME="docker.io/jgrumboe/random-logger"
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=image::${IMAGE_NAME}
          docker build -f Dockerfile -t "$IMAGE_NAME":"$VERSION" .

      - name: Scan for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ steps.build.outputs.image }}:${{ steps.build.outputs.version }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - id: set_state_final
        if: always()
        name: Set deployment status
        uses: rsotnychenko/deployment-status-update@0.2.0
        with:
          status: ${{ job.status }}
          run_id: ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
