name: PR

on:
  pull_request:
jobs:
  Build-and-check-for-vulnerabilities:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: toko-bifrost/ms-teams-deploy-card@master
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MSTEAMS_WEBHOOK }}

      - name: Start GitHub Deployments
        uses: bobheadxi/deployments@v0.4.3
        with:
          # GitHub token
          token: ${{ github.token }}
          # One of 'start' and 'finish'
          step: start
          # Description to set in status
          desc: Description of deployment ${{ github.run_id }}
          # The name of the deployment environment for Github. (Required for `start` and `deactivate-env` only)
          env: Prod
          # The deployment id to update (if specified during `start`, the deployment will be updated instead of a new one created)
          deployment_id: ${{ github.run_id }}

      - name: Build image
        id: build
        run: |
          VERSION=${{ github.sha }}
          IMAGE_NAME="docker.io/jgrumboe/random-logger"
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=image::${IMAGE_NAME}
          docker build -f Dockerfile -t "$IMAGE_NAME":"$VERSION" .

      - name: Scan for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ steps.build.outputs.image }}:${{ steps.build.outputs.version }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Finish GitHub Deployments
        uses: bobheadxi/deployments@v0.4.3
        with:
          # GitHub token
          token: ${{ github.token }}
          # One of 'start' and 'finish'
          step: finish
          # Description to set in status
          desc: Description of deployment ${{ github.run_id }}
          # The deployment id to update (if specified during `start`, the deployment will be updated instead of a new one created)
          deployment_id: ${{ github.run_id }}
          # The deployment status. (For `finish` only):
          status: ${{ job.status }}
